### ISSUE TITLE
Some question about common image corruptions experiment

### ISSUE THREAD

**Issue by ZhenglinZhou** [tejas-gokhale/AGAT#1]
Hi Tejas, thanks for your great work. 
Recently, I'm trying to test AGAT on CIFAR10-C. But the results I reproduce confused me:
![results](https://user-images.githubusercontent.com/42434623/125416810-c9bc6a72-9a0a-475f-9b49-b976e272d781.png)

The shell code: 
`python test_ours.py --dataroot /media/sdb1/datasets/cifar10-c/ --shared layer2 --rotation_type expand --group_norm 8 --resume --ckpt ./results/cifar10_agat_blur_noise/ckpt_final.pth`

I focus on the highest severity levels of corruptions. The [Src.] and [Avg.] are similar with the result shown in paper, but the corruption column has a 2-3% difference. Could you give me some advice?

**Comment by tejas-gokhale** [comment]
Hi @zzl-pointcloud -- thanks for reproducing the results.  I ran the test code again, and got the following results:

blur	        0.7488 0.7575 0.5036 0.7516 0.7005
noise 	0.7594 0.6844 0.6469 0.7511 0.7129
b+n		0.7627 0.7226 0.6747 0.7328 0.7225

So it seems that the avg. on CIFAR-10-C severity=5 that we've reported in the paper is accurate.  There does seem to be a discrepancy in W/B/N/D categories.   I will look into it.
